### ISSUE TITLE
Link broken in OpenDSS-CIM tech note

### ISSUE THREAD

**Issue by jaimiosyncrasy** [GRIDAPPSD/CIMHub#20]
In this tech note
[https://github.com/GRIDAPPSD/CIMHub/blob/master/doc/Common_Information_Model.pdf](https://github.com/GRIDAPPSD/CIMHub/blob/master/doc/Common_Information_Model.pdf)
it says 'A valid power flow model requires al six, with a possible exception of GEO. For convenience, OpenDSS can export all six to a single file. An open-source tool to combine them will also be provided at [5].'
But the reference to [5] which is [https://github.com/GRIDAPPSD/tree/develop](https://github.com/GRIDAPPSD/tree/develop) is a broken link

Could you clarify what are the set/type of files that the CIM export function requires of OpenDSS? It is not clear from the example folder what are inputs vs. outputs

**Comment by temcdrm** [comment]
The link from the document actually includes CIMHub in the URL, i.e., [https://github.com/GRIDAPPSD/CIMHub/tree/develop](https://github.com/GRIDAPPSD/CIMHub/tree/develop.) It still seems to work.  Did you manually type it with a mistake?

I believe the link can be updated with an actual tool location, since it has been completed.  Also, we can say more about the file types.

**Comment by temcdrm** [comment]
Fixed by commit 83a00a1
